module.exports={
    PRODUCT_COLLECTION:"Products",
    USER_COLLECTION:'users',
    CART_COLLECTION:'carts',
    ORDER_COLLECTION:'orders',
    ADMIN_COLLECTION:'admin',
    WISHLIST_COLLECTION:'wishlists',
    ADDRESS_COLLECTION:'addresses'
}
